INSERT INTO settings (name, value) VALUES
  ('site_title', 'LLDCard 卡密管理系统'),
  ('site_subtitle', '卡密管理与验证平台'),
  ('copyright_text', 'LLDCard'),
  ('contact_qq_group', ''),
  ('contact_wechat_qr', ''),
  ('contact_email', ''),
  ('api_enabled', '1'),
  ('sender_name', 'LLDCard'),
  ('notify_user_reg', '0'),
  ('notify_order_create', '0'),
  ('notify_key_used', '0'),
  ('notify_sys_maint', '0'),
  ('notify_sec_alert', '0'),
  ('systemName', 'LLDCard 卡密管理系统'),
  ('systemDescription', '卡密管理与验证平台'),
  ('defaultLanguage', 'zh-CN'),
  ('timezone', 'Asia/Shanghai'),
  ('autoBackup', 'true'),
  ('backupFrequency', 'daily'),
  ('backupRetention', '7'),
  ('dataCompression', 'true'),
  ('payment_enabled', 'false'),
  ('qqLogin', 'false'),
  ('authenticatorLogin', 'false'),
  ('aggregatedLogin', 'false')
ON DUPLICATE KEY UPDATE value = VALUES(value);